### ISSUE TITLE
3.5里创建节点组会报错了

### ISSUE THREAD

**Issue by chenpaner** [atticus-lv/color_helper#2]
Python: Traceback (most recent call last):
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\color_helper-master\ops\op_create_nodes_from_palette.py", line 36, in invoke
    self.create_node_group(palette, create=event.shift)
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\color_helper-master\ops\op_create_nodes_from_palette.py", line 61, in create_node_group
    nt.links.new(node.outputs[0], node_output.inputs[i])
IndexError: bpy_prop_collection[index]: index 1 out of range, size 1

**Comment by chenpaner** [comment]
你好，好像3.5里用代码新建节点组要预先写好组输入和组输出的各个端口才行了，之前的版本不用预先写出，请问这插件能修复这个问题么，我色板里有4个颜色，但生成的对应节点组没法生成对应的颜色输出端口，谢谢了

**Comment by atticus-lv** [comment]
这段时间有点忙，我会尽快修复这个问题。3.5和3.6对创建接口的改动都比较大

**Comment by chenpaner** [comment]
哦哦，明白了 工作重要，我还以为是之前没说明白问题才重新说明下，等你忙完再改呗

**Comment by chenpaner** [comment]
感谢跟新了，我在3.6里用了最新版本插件，有个问题啊，就是我在N面板修改颜色后点击更新后，节点组的输出端口会自动翻倍数量，我录了个GIF演示了下
![动画2](https://github.com/atticus-lv/color_helper/assets/107256886/46aa8869-2295-4dc5-9a13-027679feeb9b)

还有就是按住shift添加节点组时会报错Python: Traceback (most recent call last):
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Big addons\addons\color_helper-master\ops\op_create_nodes_from_palette.py", line 36, in invoke
    self.create_node_group(palette, create=event.shift)
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Big addons\addons\color_helper-master\ops\op_create_nodes_from_palette.py", line 95, in create_node_group
    loc_x, loc_y = bpy.context.space_data.cursor_location
AttributeError: 'SpaceView3D' object has no attribute 'cursor_location'

然后就是建议下，节点组的输出端的名字能否加个序列号啊，比如颜色1，颜色2......这样好找点

**Comment by chenpaner** [comment]
你好，我针对bl4.0修复了上面的错误，修改的是op_create_nodes_from_palette.py里CH_OT_create_nodes_from_palette操作里的 create_node_group函数，修改的地方我都加上注释了，这是我修改后的代码
```
    def create_node_group(self, palette, create):
        if palette.node_group is not None:
            nt = palette.node_group
            for node in nt.nodes:
                nt.nodes.remove(node)
            #上面虽然删除了节点组里所有节点，包括组输出节点，但节点组的输出端口还是在的，用下面的方法删除输出端
            for item in nt.interface.items_tree:
                if item.item_type == 'SOCKET':
                    if item.in_out == 'OUTPUT'or item.in_out == 'INPUT':
                        nt.interface.remove(item)

        else:
            nt = bpy.data.node_groups.new(palette.name, 'ShaderNodeTree')
            palette.node_group = nt

        loc_x, loc_y = 0, 0
        node_output = nt.nodes.new('NodeGroupOutput')
        node_output.location = len(palette.colors) * 150 + 200, 0
        node_input = nt.nodes.new('NodeGroupInput')
        node_input.location = (len(palette.colors) - 2) * 150, -(len(palette.colors) + 3) * 50

        for i, color in enumerate(palette.colors):
            color = color.color
            colornode = nt.nodes.new('ShaderNodeRGB')
            colornode.outputs[0].default_value = color
            colornode.location = loc_x + i * 150, loc_y - i * 50

            #添加颜色输出端口，端口名加上序号，方便知道那个端口是色板里第几个颜色
            if bpy.app.version >= (4, 0, 0):
                nt.interface.new_socket(name="Color"+"  _"+str(i+1), in_out='OUTPUT',socket_type='NodeSocketColor')

            nt.links.new(colornode.outputs[0], node_output.inputs[i])

        node_ramp = nt.nodes.new(type="ShaderNodeValToRGB")
        node_ramp.location = node_input.location[0] + 200, node_input.location[1]
        node_ramp.color_ramp.elements.remove(node_ramp.color_ramp.elements[0])
        node_ramp.color_ramp.elements[0].position = 0
        for i, color_item in enumerate(palette.colors):
            if i > 0:
                node_ramp.color_ramp.elements.new(position=1 / (len(palette.colors) - 1) * i)
            node_ramp.color_ramp.elements[i].color = color_item.color

        #改为4.0的新增渐变的端口
        if bpy.app.version >= (4, 0, 0):
            nt.interface.new_socket(name="Ramp Fac", in_out='INPUT',socket_type='NodeSocketFloat')
            nt.interface.new_socket(name="Ramp", in_out='OUTPUT',socket_type='NodeSocketColor')

        nt.links.new(node_input.outputs[0], node_ramp.inputs[0])
        nt.links.new(node_ramp.outputs[0], node_output.inputs["Ramp"])

        if not create: return
        # 检查当前操作空间是否是在材质节点编辑器里
        if bpy.context.area.type != 'NODE_EDITOR' or bpy.context.space_data.tree_type != 'ShaderNodeTree':
            self.report({'WARNING'}, "在节点编辑器里按Shift后才会自动添加节点组！")
            return

        loc_x, loc_y = bpy.context.space_data.cursor_location
        bpy.ops.node.select_all(action='DESELECT')
        edit_tree = bpy.context.space_data.edit_tree

        if edit_tree != nt and not (edit_tree.nodes.active and
                                    hasattr(edit_tree.nodes.active, 'node_tree') and
                                    getattr(edit_tree.nodes.active, 'node_tree') == nt):
            group_node = edit_tree.nodes.new('ShaderNodeGroup')
            group_node.node_tree = nt

            group_node.location = loc_x - bpy.context.region.width, loc_y

            bpy.ops.transform.translate('INVOKE_DEFAULT')
```

**Comment by atticus-lv** [comment]
感谢修复，测试过没问题.已发布到release
